import Head from 'next/head'

import Header from './Components/header/Header'
import Timeline from './Components/timeline/Timeline'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
      </Head>
      <Header />
      <h1>Hello</h1>
      <Timeline />
    </div>
  )
}
