export const INITIALIZE_GROUPS = 'INITIALIZE_GROUPS'

export const OPEN_NEW_GROUP_FORM = 'OPEN_NEW_GROUP_FORM'
export const CLOSE_NEW_GROUP_FORM = 'CLOSE_NEW_GROUP_FORM'

export const ADD_NEW_GROUP = 'ADD_NEW_GROUP'
